
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 20 00:14:55 CST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 12;
  public static final int TIPO = 28;
  public static final int POR = 33;
  public static final int INPUT = 32;
  public static final int SEPARADOR = 8;
  public static final int FIN = 9;
  public static final int FOR = 20;
  public static final int REF = 10;
  public static final int WRITE = 30;
  public static final int NOT = 41;
  public static final int ELSEIF = 18;
  public static final int IGUAL = 13;
  public static final int TYPE = 38;
  public static final int OPREL = 27;
  public static final int NUM = 23;
  public static final int EXIT = 39;
  public static final int NEXT = 21;
  public static final int LOOP = 14;
  public static final int IF = 15;
  public static final int WRITELN = 31;
  public static final int SALTOCADENA = 42;
  public static final int DIM = 7;
  public static final int EOF = 0;
  public static final int PARIZQ = 4;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int CADENA = 29;
  public static final int MENOS = 36;
  public static final int ERROR = 37;
  public static final int NAME = 26;
  public static final int ELSE = 17;
  public static final int PUNTO = 40;
  public static final int TO = 5;
  public static final int WHILE = 22;
  public static final int THEN = 16;
  public static final int END = 19;
  public static final int FALSE = 25;
  public static final int AS = 6;
  public static final int PARDER = 3;
  public static final int ENTRE = 34;
  public static final int SUB = 11;
  public static final int DO = 2;
  public static final int MAS = 35;
}

